### ISSUE TITLE
Random text position doesn't actually cause random text position. 

### ISSUE THREAD

**Issue by ThinkSalat** [OrangeJedi/Aerial#138] opened 2023-03-16 22:22 UTC
**Describe the bug**
I set the "random" text  to what I want, but it never even shows up on the screen. using an lg c1 60"

**To Reproduce**
select random location for text and test it

**Expected behavior**
It puts the text in random locations to prevent burn in on oled

**Aerial Version**
latest

**Additional context**
Would be really nice because I like the text display. Unfortunately it comes with potential burn in issues on an oled

**Comment by OrangeJedi** [comment] 2023-03-23 15:46
I was not able to reproduce this bug. The random text option is working just fine for me. 

What type of text are you trying to display? What is `Random Change Speed` on the text options menu set to? Both these could be effecting it.

**Comment by OrangeJedi** [comment] 2023-03-23 17:09
Ok, I think I found the bug. Aerial don't trigger the random text to load until after the `Random Change Speed` time has passed. If you keep Aerial open for 30 seconds it should work as expected. Obviously this needs to be fixed and I'll slate it for the next update. Thanks for pointing this out!

**Comment by ThinkSalat** [comment] 2023-03-23 17:13
Great! Good find

**Comment by OrangeJedi** [comment] 2023-06-07 02:24
Fixed in `v1.2.1`

**Closed by OrangeJedi** 2023-06-07 02:24 UTC
Labels: bug
