### ISSUE TITLE
hide mouse cursor

### ISSUE THREAD

**Issue by smoothnobody** [OrangeJedi/Aerial#96] opened 2022-04-29 01:14 UTC
i've been using the other version from cDima this is based from. i just installed this version and immediately noticed the mouse cursor stays on screen when the screensaver starts. it's kinda an eye sore to see the mouse in the middle of these awesome landscapes. since the other version does not have this issue i know it's fixable. hopefully this gets fixed.

**Comment by tompazourek** [comment] 2022-05-08 11:24
Same issue here. The mouse cursor is very annoying...

Maybe it's because of Electron?

**Comment by tompazourek** [comment] 2022-05-08 11:26
btw. seems like a dupe of #79

**Comment by OrangeJedi** [comment] 2022-10-06 01:18
It is surprisingly hard to hide a cursor. But this latest fix in v1.0.0 should do the trick.

**Closed as completed** 2022-10-06 01:19 UTC
Labels: enhancement
