### ISSUE TITLE
The app doesn't play the same video on all screens every time

### ISSUE THREAD

**Issue by HeLiOn--PrImE** [OrangeJedi/Aerial#46] opened 2020-06-04 10:37 UTC
The same video every screen setting is checked, but the app often plays different videos on each screen.

**To Reproduce**
1. Make sure the right setting is made (to play the same video on all screens)
2. Click on 'preview', or wait for the screensaver to launch
3. Notice that different videos are played.

**Expected behavior**
When I make that setting, I expect the same video to be played on both screens.

**Aerial Version**
Beta 0.5.3

**Additional context**
It doesn't happen all the time. Sometimes the same video is played.

I recorded a video with my phone to show the behavior.
[Untitled.zip](https://github.com/OrangeJedi/Aerial/files/4729409/Untitled.zip)

**Comment by abeulink** [comment] 2020-06-08 10:34
Indeed, I also have same problem... 
I have 3 screen and I give you more pictures.

![IMG_5021](https://user-images.githubusercontent.com/26407519/84020655-70699900-a983-11ea-86f0-a0c2e88b86d5.jpg)
![IMG_5023](https://user-images.githubusercontent.com/26407519/84020658-71022f80-a983-11ea-8cf3-cd737695b702.jpg)

Aerial Version Beta 0.5.3
Windows 10 version 1909 (build 18363.836)

**Comment by VasilisPat** [comment] 2020-06-08 11:45
I checked through the settings menu and it seems that indeed sometimes the app doesn't play the same video on all screens, although the option is selected. A way that I tried out and it seems to work for me is:
- Cache all the videos of your choice
- Disable video processing under Playback Settings
- Enable the "Play the same video on all screens" option under Multi-Screen Settings

This seems to have solved the issue that you have reported temporarily. Please share a feedback if this method works, so identification of the cause can be made easier.
I am sure the developer will get back to you with more information and a solution to the problem.

**Comment by HeLiOn--PrImE** [comment] 2020-06-08 13:36
@VasilisPat What do you mean by "Cache all the videos of your choice"?
The app downloaded everything in the cache, and I don't really intend to get rid of any of the videos.

"Play the same video on all screens" is already enabled, soo...  that leaves me with disabling all video processing?

**Comment by OrangeJedi** [comment] 2020-06-08 14:16
I think this is more of a problem with the app itself. Caching the videos should help, but I don't think any setting changes will completely solve it. The code to play the same video on each screen isn't as well done as I would like it to be. I'll take a look at it.

@HeLiOn--PrImE @abeulink Does the same video play some of the time? And when the video are different will screens often play the same video that another screen has almost finished or just stopped playing?

**Comment by HeLiOn--PrImE** [comment] 2020-06-08 15:43
@OrangeJedi Yes, that does happen. Again, not 100% of the times, but it does. The playback is just de-synchronized.

I should also mention that after awhile the playback completely stops and both of the screens remain black. Not sure if this is related or if should I create a different ticket for it.

**Comment by HeLiOn--PrImE** [comment] 2020-06-09 09:53
Update:
I disabled video processing, and it doesn't seem to solve the issue.
On my main monitor the video froze, while on the secondary, the playback continued.
I can't say how much time passed, because had I left the house.
Video attached in a zip file
[20200609_124718.zip](https://github.com/OrangeJedi/Aerial/files/4751341/20200609_124718.zip)

**Comment by VasilisPat** [comment] 2020-06-09 09:58
For sure disabling video processing will create some form of playback issues, some of them noticable and some of them not. In my case it doesn't seem to have any visual problem, but results may vary. Again I must say that this is a work around that might work for some users, as it did in my case (at least until now that I am testing it).

**Comment by OrangeJedi** [comment] 2020-09-21 16:45
Fixed in [v0.5.4](https://github.com/OrangeJedi/Aerial/releases/tag/v0.5.4-beta). Please create a new issue if you still get this problem.

**Closed by OrangeJedi** 2020-09-21 16:45 UTC
Labels: bug
