### ISSUE TITLE
Love it when it works. I get these types of errors all the time.

### ISSUE THREAD

**Issue by madman2012** [OrangeJedi/Aerial#160] opened 2023-07-18 02:02 UTC
**Describe the bug**
Will not run.

**To Reproduce**
When the screen saver tries to run I normally get a java error like this. 

**Expected behavior**

**Screenshots**
![Screen Saver Error](https://github.com/OrangeJedi/Aerial/assets/5844691/01bc3b9b-f0f7-4b9c-8e35-15b616cc935f)

**Aerial Version**
LATEST

**Additional context**

**Comment by kloodhu** [comment] 2023-08-02 09:41
same here.

**Comment by skbtwiz** [comment] 2023-08-14 02:29
Can confirm, same is happening with latest update.

**Comment by grendizerus** [comment] 2023-08-15 14:58
I have the same problem I'm on v1.2.1

**Comment by OrangeJedi** [comment] 2023-10-14 21:24
Duplicate of #143. I've been digging around I think I found the source of this bug. Hopefully a fix fill come soon.

**Closed as completed by OrangeJedi** 2023-10-14 21:24 UTC
Labels: bug, duplicate
