### ISSUE TITLE
Query the Windows WakeLock Api 

### ISSUE THREAD

**Issue by TheGreyDiamond** [OrangeJedi/Aerial#113] opened 2022-10-27 20:00 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the screensaver kicks in while watching a video. 

**Describe the solution you'd like**
Prevent the screensaver from kicking in while watching a video. Maybe query the `powercfg /requests` command.

**Comment by OrangeJedi** [comment] 2022-11-03 22:22
This is certainly a big issue (see #114). Thanks for suggesting a solution! I'll look into querying the `powercfg` command and see if that will be able to fix this bug.

**Comment by OrangeJedi** [comment] 2022-11-03 22:41
Ok, a quick look at `powercfg /requests` shows that while it does provide the necessary information to show if an app is requesting that a computer not sleep, the command must be run with administrative privileges. Currently Aerial isn't an elevated app nor do I want it to be. I am now looking into other ways of looking at powercfg requests.

**Comment by OrangeJedi** [comment] 2022-11-11 03:07
As it appears the wakelock api can't be used right now I am going to close this and move discussion of the issue to #114 where the issue is easier to find.

**Closed by OrangeJedi** 2022-11-11 03:07 UTC
Labels: enhancement
