### ISSUE TITLE
Add option for multiple types of text display

### ISSUE THREAD

**Issue by jonathanmwood** [OrangeJedi/Aerial#70] opened 2020-11-13 09:17 UTC
Love this app!

I think it would be great if we could add more than one type of text e.g. location information in the bottom left and time and date in the top right. Is this possible? 

Thanks for all your work!

**Comment by VasilisPat** [comment] 2020-11-13 09:24
Hello there, 

Yes the text customization you want can be made. Each part of the screen that text can be added is represented by a dot. Navigate to the Text menu, after that to the position sub-menu. Click the dot on the position you like to add the text type of your choice. Text types for each position can be selected by a drop down menu on top right corner of each dot's settings page.

For more information you can consult the [user manual](https://github.com/OrangeJedi/Aerial/blob/master/documentation/Aerial%20for%20Windows%20-%20User%20Manual.pdf) (Text type selection is reffered at page 7).

**Comment by jonathanmwood** [comment] 2020-11-13 14:09
Got it! Thanks.

Apologies, I didn't realise each node could show a distinct type of text.

I still think it would be great to be able to do something like the following on the one node:

> **Over the Mojave desert**
> Monday, 2nd November
> 14:00

e.g. multiple text types with distinct formatting on a single node with a line break between them.

Is this possible?

**Comment by OrangeJedi** [comment] 2022-10-06 01:28
This is a great idea! It should be possible, My biggest concern is how the UI to set it up would work.

For now, you can use the HTML option to code on multiple lines, but it would be tricky to make them dynamic.

**Comment by OrangeJedi** [comment] 2022-10-06 04:23
Ok, I just saw that this is a duplicate of #26. I will close this issue and move all discussion there.

**Closed by OrangeJedi** 2022-10-06 04:23 UTC
Labels: duplicate, enhancement
