### ISSUE TITLE
Choosing the cache folder for the videos

### ISSUE THREAD

**Issue by Aleatoire** [OrangeJedi/Aerial#14] opened 2020-04-08 10:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by OrangeJedi** [comment] 2020-04-08 15:53
This looks to be an incomplete duplicate of #15... I'll close it and we can move discussion there.

**Closed by OrangeJedi** 2020-04-08 15:53 UTC
Labels: enhancement
